# Binomial Classification in Keras

In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
import tensorflow.keras.models as models
import tensorflow.keras.layers as layers

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

import sys
print('Python Ver. : ', sys.version)
print('Tensorflow Ver. : ', tf.__version__)

Python Ver. :  3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)]
Tensorflow Ver. :  2.7.0


## 데이터 로드 (defect_test_data.csv)

In [2]:
data = np.loadtxt('defect_test_data.csv', delimiter=',', dtype=str, skiprows=1)

In [3]:
# 첫 번째 데이터 값 확인
data[0, :]

array(['11', '52Q150238RJB_2_CRACK', '0', 'CRACK', '400', '0x0', '2001',
       '3079', '1994', '3075', '148', '17', '12', '4', '45', '0.687',
       '0.363', '225', '56.614', '94', '58.629', '46', '153', '0',
       'FALSE'], dtype='<U20')

In [4]:
# x_data와 y_data 분리
x_data = data[:, 6:-1]
y_data = data[:, [-1]]

In [5]:
# x_data의 타입 변경
x_data = x_data.astype(np.float)

c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [6]:
# x_data의 형태(shape) 확인
x_data.shape

(55, 18)

In [7]:
y_unique, y_int = np.unique(y_data, return_inverse=True)

In [8]:
y_unique, y_int

(array(['FALSE', 'TRUE'], dtype='<U20'),
 array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64))

## 모델 구성

Keras로 모델을 만드는 세 가지 방법이 있다.  
1. Sequential API
2. Functional API
3. Model Subclassing

In [9]:
# Sequential API
model = models.Sequential()
model.add(layers.Dense(36, activation='relu', input_shape=(18,)))
model.add(layers.Dense(36, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [10]:
# 모델의 구조 살펴 보기
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 36)                684       
                                                                 
 dense_1 (Dense)             (None, 36)                1332      
                                                                 
 dense_2 (Dense)             (None, 1)                 37        
                                                                 
Total params: 2,053
Trainable params: 2,053
Non-trainable params: 0
_________________________________________________________________


## 모델 컴파일

In [11]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

## 모델 훈련

In [22]:
model.fit(x_data, y_int, batch_size=10, epochs=200, shuffle=False)

Epoch 1/200
6/6 [==============================] - 0s 400us/step - loss: 5.9808e-10 - accuracy: 1.0000
Epoch 2/200
6/6 [==============================] - 0s 601us/step - loss: 7.2526e-10 - accuracy: 1.0000
Epoch 3/200
6/6 [==============================] - 0s 601us/step - loss: 6.6133 - accuracy: 0.9636
Epoch 4/200
6/6 [==============================] - 0s 601us/step - loss: 17.3479 - accuracy: 0.9273
Epoch 5/200
6/6 [==============================] - 0s 601us/step - loss: 8.0737 - accuracy: 0.9273
Epoch 6/200
6/6 [==============================] - 0s 600us/step - loss: 3.3655 - accuracy: 0.9455
Epoch 7/200
6/6 [==============================] - 0s 600us/step - loss: 3.0160 - accuracy: 0.9455
Epoch 8/200
6/6 [==============================] - 0s 601us/step - loss: 5.3191 - accuracy: 0.9273
Epoch 9/200
6/6 [==============================] - 0s 400us/step - loss: 0.7841 - accuracy: 0.9818
Epoch 10/200
6/6 [==============================] - 0s 400us/step - loss: 6.3653 - accuracy: 0.9273


6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 81/200
6/6 [==============================] - 0s 400us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 82/200
6/6 [==============================] - 0s 400us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 83/200
6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 84/200
6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 85/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 86/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 87/200
6/6 [==============================] - 0s 400us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 88/200
6/6 [==============================] - 0s 400us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 89/200
6/6 [==============================] - 0s 400us/step - loss: 4.9

6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 159/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 160/200
6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 161/200
6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 162/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 163/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 164/200
6/6 [==============================] - 0s 600us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 165/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 166/200
6/6 [==============================] - 0s 601us/step - loss: 4.9666e-10 - accuracy: 1.0000
Epoch 167/200
6/6 [==============================] - 0s 600us/step - 

## 예측하기

In [23]:
y_predict = model.predict(x_data) > 0.5 # 0.5 보다 크면 True, 아니면 False
y_predict = y_predict + 0 # Convert boolean to int
y_predict = np.squeeze(y_predict) # 차원 축소

In [24]:
y_predict

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [25]:
y_int

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [26]:
y_int - y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [50]:
# 데이터 한 개 예측하기
y_predict_one = model.predict(x_data[4,:].reshape(1,18))

In [51]:
y_predict_one

array([[1.]], dtype=float32)

## 모델 저장하기

In [52]:
#from keras.models import load_model
model.save('bc_model.h5')