# Binomial Classification in Keras

In [16]:
# TensorFlow and tf.keras
import tensorflow as tf
import tensorflow.keras.models as models
import tensorflow.keras.layers as layers

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

import sys
print('Python Ver. : ', sys.version)
print('Tensorflow Ver. : ', tf.__version__)

Python Ver. :  3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
Tensorflow Ver. :  2.6.0


## 데이터 로드 (defect_test_data.csv)

In [22]:
data = np.loadtxt('defect_test_data.csv', delimiter=',', dtype=str, skiprows=1)

In [49]:
# 첫 번째 데이터 값 확인
data[0, :]

array(['11', '52Q150238RJB_2_CRACK', '0', 'CRACK', '400', '0x0', '2001',
       '3079', '1994', '3075', '148', '17', '12', '4', '45', '0.687',
       '0.363', '225', '56.614', '94', '58.629', '46', '153', '0',
       'FALSE'], dtype='<U20')

In [50]:
# x_data와 y_data 분리
x_data = data[:, 6:-1]
y_data = data[:, [-1]]

In [51]:
# x_data의 타입 변경
x_data = x_data.astype(np.float)

In [52]:
# x_data의 형태(shape) 확인
x_data.shape

(55, 18)

In [39]:
y_unique, y_int = np.unique(y_data, return_inverse=True)

In [40]:
y_unique, y_int

(array(['FALSE', 'TRUE'], dtype='<U20'),
 array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64))

## 모델 구성

Keras로 모델을 만드는 세 가지 방법이 있다.  
1. Sequential API
2. Functional API
3. Model Subclassing

In [35]:
# Sequential API
model = models.Sequential()
model.add(layers.Dense(36, activation='relu', input_shape=(18,)))
model.add(layers.Dense(36, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

In [36]:
# 모델의 구조 살펴 보기
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 36)                684       
_________________________________________________________________
dense_2 (Dense)              (None, 36)                1332      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 37        
Total params: 2,053
Trainable params: 2,053
Non-trainable params: 0
_________________________________________________________________


## 모델 컴파일

In [45]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

## 모델 훈련

In [46]:
model.fit(x_data, y_int, batch_size=10, epochs=100, shuffle=False)

Epoch 1/100
6/6 [==============================] - 1s 2ms/step - loss: 20.9755 - accuracy: 0.9091
Epoch 2/100
6/6 [==============================] - 0s 2ms/step - loss: 15.6856 - accuracy: 0.8727
Epoch 3/100
6/6 [==============================] - 0s 2ms/step - loss: 6.9457 - accuracy: 0.8909
Epoch 4/100
6/6 [==============================] - 0s 2ms/step - loss: 2.0464 - accuracy: 0.9455
Epoch 5/100
6/6 [==============================] - 0s 2ms/step - loss: 9.7432 - accuracy: 0.8909
Epoch 6/100
6/6 [==============================] - 0s 1ms/step - loss: 6.9433 - accuracy: 0.8909
Epoch 7/100
6/6 [==============================] - 0s 2ms/step - loss: 4.0219 - accuracy: 0.9455
Epoch 8/100
6/6 [==============================] - 0s 2ms/step - loss: 4.7004 - accuracy: 0.8909
Epoch 9/100
6/6 [==============================] - 0s 2ms/step - loss: 2.2470 - accuracy: 0.9636
Epoch 10/100
6/6 [==============================] - 0s 2ms/step - loss: 7.2295 - accuracy: 0.9091
Epoch 11/100
6/6 [=========

## 예측하기

In [64]:
y_predict = model.predict(x_data) > 0.5 # 0.5 보다 크면 True, 아니면 False
y_predict = y_predict + 0 # Convert boolean to int
y_predict = np.squeeze(y_predict) # 차원 축소

In [65]:
y_predict

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [67]:
y_int

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [70]:
y_int - y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)